Internal Server Error: /
Traceback (most recent call last):
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework_swagger\views.py", line 32, in get
    schema = generator.get_schema(request=request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 156, in get_schema
    links = self.get_links(None if public else request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 143, in get_links
    link = view.schema.get_link(path, method, base_url=self.url)
AttributeError: 'AutoSchema' object has no attribute 'get_link'
Not Found: /favicon.ico
Internal Server Error: /api/docs
Traceback (most recent call last):
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework_swagger\views.py", line 32, in get
    schema = generator.get_schema(request=request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 156, in get_schema
    links = self.get_links(None if public else request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 143, in get_links
    link = view.schema.get_link(path, method, base_url=self.url)
AttributeError: 'AutoSchema' object has no attribute 'get_link'
Internal Server Error: /api/docs
Traceback (most recent call last):
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework_swagger\views.py", line 32, in get
    schema = generator.get_schema(request=request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 156, in get_schema
    links = self.get_links(None if public else request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\schemas\coreapi.py", line 143, in get_links
    link = view.schema.get_link(path, method, base_url=self.url)
AttributeError: 'AutoSchema' object has no attribute 'get_link'
Internal Server Error: /api/docs
Traceback (most recent call last):
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 55, in render
    return render(
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "C:\X1_Enter\Web Development\community projects\EdTech-Web\venv\lib\site-packages\django\template\defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
nested_admin
rest_framework
static
tz
Not Acceptable: /api/docs
Not Found: /api/docs
Not Found: /api/docs
